# App
spring.application.name=country-explorer
server.port=8080

# MySQL Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/m295_country_explorer?useSSL=false&serverTimezone=Europe/Zurich&allowPublicKeyRetrieval=true
spring.datasource.username=m295_user
spring.datasource.password=1111111111

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Run data.sql on startup (also for MySQL)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
