# ---------------------------------------
# Application
# ---------------------------------------
spring.application.name=country-explorer

# ---------------------------------------
# MySQL Datasource
# ---------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/m223_country_explorer?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Zurich
spring.datasource.username=m223_user
spring.datasource.password=m223pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ---------------------------------------
# JPA / Hibernate
# ---------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ---------------------------------------
# SQL Init
# ---------------------------------------
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ---------------------------------------
# Server
# ---------------------------------------
server.port=8080

# ---------------------------------------
# JWT Security
# ---------------------------------------
myapp.jwtSecret=OEQ0NTM0QUFCQzM0NUQ4MjY4OUY3QkFCQzM0NUQ4QTdBNDY5OUFCQzM0NUQ4MTlDT0ZFMTgw
myapp.jwtExpirationMs=1000000

# ---------------------------------------
# Logging
# ---------------------------------------
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG